MONGODB_HOST: mongodb-{{ env }}.adarshdevopslearn.online
REDIS_HOST: redis-{{ env }}.adarshdevopslearn.online
MYSQL_HOST: mysql-{{ env }}.adarshdevopslearn.online
RABBITMQ_HOST: rabbitmq-{{ env }}.adarshdevopslearn.online
CATALOGUE_HOST: catalogue-{{ env }}.adarshdevopslearn.online
CART_HOST: cart-{{ env }}.adarshdevopslearn.online
SHIPPING_HOST: shipping-{{ env }}.adarshdevopslearn.online
USER_HOST: user-{{ env }}.adarshdevopslearn.online
PAYMENT_HOST: payment-{{ env }}.adarshdevopslearn.online
