- name: Install Maven
  package:
    name: maven
    state: present

- name: install Maven dependencies
  command: mvn clean package
  args:
    chdir: /app

- name: Move jar file
  command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app