ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb.adarshdevopslearn.online
REDIS_HOST: redis.adarshdevopslearn.online
MYSQL_HOST: mysql.adarshdevopslearn.online
RABBITMQ_HOST: rabbitmq.adarshdevopslearn.online
