- name: Setting Payment
  hosts: frontend
  become: yes
  tasks:
    - name: Install Python
      command: dnf module enable nginx:1.24 -y
    - name: Install Nginx
      package:
        name: nginx
        state: present
    - name:


