[local]
localhost

[mongodb]
mongodb.adarshdevopslearn.online

[mysql]
mysql.adarshdevopslearn.online

[redis]
redis.adarshdevopslearn.online

[rabbitmq]
rabbitmq.adarshdevopslearn.online

[catalogue]
catalogue.adarshdevopslearn.online

[user]
user.adarshdevopslearn.online

[cart]
cart.adarshdevopslearn.online

[shipping]
shipping.adarshdevopslearn.online

[payment]
payment.adarshdevopslearn.online

[dispatch]
dispatch.adarshdevopslearn.online

[frontend]
adarshdevopslearn.online