- name: Install RabbitMQ
  hosts: rabbitmq
  become: yes
  tasks:
    - name: copy rabbitmq repo file
      copy:
        src: ./rabbitmq.repo
        dest: /etc/yum.repos.d/

    - name: Install  Rabbitmq server
      package:
        name: rabbitmq-server
        state: present
    - name: Enable and start service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
    - name: create rabbitmq user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        topic_permissions:
          - vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        state: present
    - name: Enable and start service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes