- name: "{{ component }} setup"
  import_role:
    name: common
    tasks_from: app-setup

- name: Python setup
  import_role:
    name: common
    tasks_from: python-setup

- name: system-setup
  import_role:
    name: common
    tasks_from: system-setup

- name: restart
  import_role:
    name: common
    tasks_from: restart