- name: "{{ component }} setup"
  import_role:
    name: common
    tasks_from: app-setup

- name: Java setup
  import_role:
    name: common
    tasks_from: java-setup

- name: Install SQl client
  package:
    name: mysql
    state: present

- name: System setup
  import_role:
    name: common
    tasks_from: system-setup


- name: install python dependencies
  pip:
    name: PyMySQL
    executable: pip3.9

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: "{{ Mysql_ClientIUser }}"
    login_password: "{{ Mysql_ClientPassword }}"
    login_host: "{{ MYSQL_HOST }}"
    target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

- name: Service restart
  import_role:
    name: common
    tasks_from: restart